'''
Docstring for even_fibonacci_numbers
<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, dots$$</p>
<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>

'''
def find_even_sum(limit):
    sum, a, b = 0, 1, 2
    while a < limit:
        # Find the even ones and add it to sum
        if a < limit and a % 2 == 0:
            sum += a
        # Update values: a becomes b, b becomes the sum
        a, b = b, a + b
    print(sum)

find_even_sum(4000000)

'''
    Better Way (Gemini)
    def even_fibonacci_generator(limit):
        a, b = 2, 8
        yield 2  # Start with the first even number
        while b < limit:
            yield b
            a, b = b, 4 * b + a

    # Now you can use it like a tool
    total = sum(even_fibonacci_generator(4000000))
    print(total)

    
'''